-- SQL to create the 'schemes' table in Supabase
-- Go to Supabase -> SQL Editor -> New Query and paste this

CREATE TABLE schemes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    income_limit TEXT,
    occupation TEXT,
    state TEXT,
    benefit TEXT,
    tags TEXT,
    url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Optional: Enable Row Level Security (RLS)
-- ALTER TABLE schemes ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public read access" ON schemes FOR SELECT USING (true);
